python MSA_parser_cleaner.py Raji_CellLine_longRead_EBV_type1 Raji_GenomiPhi_EBV_type1 AmplificationTest.aln 1
python MSA_parser_cleaner.py Raji_CellLine_longRead_EBV_type1 Raji_CellLine_shortRead_EBV_type1 AmplificationTest.aln 1
python MSA_parser_cleaner.py Raji_Rep1_PCRsWGA_EBV_type1 Raji_Rep2_PCRsWGA_EBV_type1 AmplificationTest.aln 1
python MSA_parser_cleaner.py Daudi_CellLine_EBV_type1 Daudi_D100_PCRsWGA_EBV_type1 AmplificationTest.aln 1
python MSA_parser_cleaner.py BL573_eBLFNAtumorDNA_wga_EBV_type1 BL573_eBLFNAtumorDNA_EBV_type1 AmplificationTest.aln 1
python MSA_parser_cleaner.py BL576_eBLFNAtumorDNA_wga_EBV_type2 BL576_eBLFNAtumorDNA_EBV_type2 AmplificationTest.aln 2
python MSA_parser_cleaner.py BL578_eBLFNAtumorDNA_wga_EBV_type2 BL578_eBLFNAtumorDNA_EBV_type2 AmplificationTest.aln 2
python MSA_parser_cleaner.py BL590_eBLFNAtumorDNA_wga_EBV_type1 BL590_eBLFNAtumorDNA_EBV_type1 AmplificationTest.aln 1
python MSA_parser_cleaner.py BL607_eBLFNAtumorDNA_wga_EBV_type1 BL607_eBLFNAtumorDNA_EBV_type1 AmplificationTest.aln 1

#These are for test runs.
